### ISSUE TITLE
Add button to put a post to a board

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#148]
As a user, I want to be able to put a post to a board

- Each post has the corresponding button
- The adding a post to a board form has a board selection mechanism
- There are submit and cancel buttons on the form

**Comment by ericaivarsson** [comment]
@atamankina so this should be an improvement of our current make a post functionality? Should we give the option to the user to post to several boards at the same time ? 
Should the user be able to post to his normal "My posts" at the same time he posts to a certain board?

**Comment by atamankina** [comment]
@ericaivarsson this is not an improvement, this is adding one more feature. The feature design is open and all the design questions should be addressed by the devs together with the PO.

**Comment by pr0me** [comment]
Implemented as: Adding a post to a board is only possible on creation for now.

Additional option of adding posts later on, if wanted, should be a new ticket.

**Comment by ericaivarsson** [comment]
Verified on Safari and Firefox. 

The current implementation should be sufficient, but could we add so that you can only post to boards you have subscribed to? i.e. the whole list of boards should not appear! It can become too long if the webpage gets many users who create many boards, and maybe the user wanting to post to only one board does not want to see them always in the list. (Idea for new ticket)
