### ISSUE TITLE
Create a Readme file

### ISSUE THREAD

**Issue by jkaschner** [SNDjango/server#150]
As a user I want to have a Readme file, where I can read all important information about the software.

**Comment by ericaivarsson** [comment]
Here´s an example of readme file: https://github.com/klen/django_markdown

**Comment by ericaivarsson** [comment]
Please make sure a new readme file is NOT created, as this project already has one which can be simply edited.

**Comment by ericaivarsson** [comment]
Hey guys - i started this job but I don´t think I have time to finish it. Would be great if you guys could also help me working on it. Checkout the branch i created: updateReadme-#150 and add your changes! 

I haven´t found a good way to view the changes before commiting them... sooo... at the moment there will be many commits unless someone comes up with a better solution!  ( I had to commit & Push in order to see the readme file here on github)

**Comment by ericaivarsson** [comment]
![read_me](https://user-images.githubusercontent.com/7579217/27984567-95162fe0-63d9-11e7-8717-8fd75f10643f.png)

the file looks like this now after my changes. What we need is information on installation: deployment and/or how they can just clone it and run it on their own local computer if they want. 
Also maybe info on tests?  
@tatankayotanka  @atamankina   - maybe you can add something on tests? 
 @Teszko   - would be great if you wrote something on deployment 
@jkaschner  - maybe there is something you want to add too?
