### ISSUE TITLE
Click Sign Up button to register

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#29]
As a user, I want to click on the Sign Up button after filling in Sign Up form so that I can sign up and become a website user.

Acceptance Criteria:

- clicking the Sign Up button starts checking the input fields
- input field user name should take the value up to 30 symbols
- username must be unique in the system
- e-mail input field should have the proper format like user@example.com
- password field should be not shorter than 6 symbols
- if input is valid, the user profile is created in the system, the user is being logged in and redirected to the main page
- if input is invalid, no redirect occurs and the user sees the corresponding inline error message

Error cases:

invalid user name: invalid username message
invalid password: invalid password message
invalid e-mail: invalid e-mail message

**Comment by ericaivarsson** [comment]
Hello, I have just reviewed this and unfortunately there is a strange error page comming up if what i think is the issue with using a password that is not accepted, I tried to sign up with the following: 
Username: test
email: test@test.de
password: test 
 
and i got the following error. (in attachment).

Can you please look into? I will move this back to "In progress".  I think the issue is because the password is shorter than 6 symbols. But instead of throwing me this error page I should get an error message inside the webpage, like what happens on the login view when the credentials are wrong! 

![screen shot 2017-05-28 at 16 11 01](https://cloud.githubusercontent.com/assets/7579217/26529458/6f17d570-43c0-11e7-8a52-a23c03f685de.png)

[IntegrityError_at-signup.pdf](https://github.com/SNDjango/server/files/1034219/IntegrityError_at-signup.pdf)

**Comment by ericaivarsson** [comment]
I also have a question regarding one of our acceptance criterias, it says: 
"if input is valid, the user profile is created in the system, the user is being logged in and redirected to the main page". 

At the moment, what happens is that after the user has signed up successfully, it will be redirected to the login page to put in the credentials for the newly registered account. Do we want to have it like this? in that case we must change the acceptance criteria. 

OR,  is there any way of automatically logging in the user after successful signup? (Like most webpages do). 
Thanks,
Erica

**Comment by henryk3dp** [comment]
@ericaivarsson I believe this error means you tried to register the same user twice. this is already being handled in the current version of devel. please pull a fresh devel.

**Comment by ericaivarsson** [comment]
Actually I don´t know what happened. Sorry I´m still very clumsy with Git. I deleted the cloned repository from my computer and cloned it again today, but it was not cloning a fresh version. While we are on this topic (and sorry because it does not belong to this story) how do I "update" the clone of the repository on my local computer?  "git pull..."?)

**Comment by ericaivarsson** [comment]
I have deleted the repository again and cloned again, and indeed now I have a fresh version of the repository where all these issues are fixed. I will move this to QA it looks fine for me.

**Comment by ericaivarsson** [comment]
Final question, when reviewing this, I have seen that the username has to be unique, but the same e-mail address can register several accounts. Is it not better if we avoid this? (Just one username per registered email)

**Comment by henryk3dp** [comment]
@ericaivarsson yes, `git pull origin devel` will merge an up-to-date devel into your current branch.

**Comment by atamankina** [comment]
Verified with Firefox 53.0.3 on Windows 8.1 on devel branch with latest commit e82ae04.
The following issues are reported:
Critical: handle gracefully the error when user name is empty, e-mail and password are filled in correctly #51 
Minor: fix error message when clicking sign up if all fields are empty #52
Improvement: sign up with the same e-mail only once #53
