### ISSUE TITLE
Navbar (not logged in)

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#9]
As a user, I want to see the navbar on the page so that I can have the overview and navigation possibilities

Acceptance criteria:
- Navbar is on top of the page
- Navbar is responsive
- Items: App_Name redirects to main view logged out, Sign In redirects to sign in view, Sign Up redirects to sign up
- Active navbar items correspond to displayed page

Implementation question:
- good to have is fixed navbar, but it produces content overlapping issues
- we can start with the static navbar

**Comment by tatankayotanka** [comment]
Passed tests:

 open http://127.0.0.1:8000/, main page (not logged in) ist displayed with
- 1. navbar on top, Logo (to be replaced by our real logo) on the left, Sign Up and Log In buttons on the    
       right, AC 1 is satisfied

- 2. Navbar is responsive. narrow the screen, Sign Up and Log In buttons collapse into dropdown, AC 2 is       satisfied

- 3. App_Name, here Logo redirects to main view logged out, Login redirects to Log in view, Sign Up redirects to sign up. AC  3 is satisfied

- 4. As Sign Up and Login are buttons, active nav items are not relevant anymore. Logo is still to be replaced by our logo image.

To-do suggestions:

1. Replace nav item Log with our real logo
2. Replace Login with Sign In so that Sign Up and Sign In are symmetrical and look better


Conclusion:
We will consider it as a pass for this ticket. 
@atamankina @ericaivarsson 
Please have a look and confirm.

**Comment by atamankina** [comment]
Verified with Firefox 53.0.3 on Windows 8.1 on devel branch with latest commit e82ae04

**Comment by atamankina** [comment]
Created separate ticket for logo https://github.com/SNDjango/server/issues/56
